### ISSUE TITLE
add support for outputting LDAP search filter

### ISSUE THREAD

**Issue by misterdjules** [joyent/node-krill#4]
As part of [the work to implement support for a `predicate` querystring parameter to filter through VOLAPI's ListVolumes' results](https://smartos.org/bugview/VOLAPI-15), I noticed that node-krill implemented a significant part of what needed to be done, except for rendering predicates as a string that can be used as an LDAP search filter.

I propose adding a function named `toLDAPFilterString` on the `Predicate` class' prototype. That method would return a string that represents an LDAP search filter.

I already have some work in progress that implements this, but I want to make sure it fits the use case of [VOLAPI-15](https://smartos.org/bugview/VOLAPI-15) before submitting it.

In the meantime, does that sound like a worthwhile addition?

/cc @davepacheco

**Comment by rmustacc** [comment]
Seems reasonable at a first glance to me.

**Comment by davepacheco** [comment]
Sounds good to me.

**Comment by misterdjules** [comment]
Fixed by 1252d0b0012ae96e24249e21074a3947afb4ae3c.
