### ISSUE TITLE
`toLDAPFilterString` returns invalid LDAP search filter for empty predicates

### ISSUE THREAD

**Issue by misterdjules** [joyent/node-krill#8]
I feel embarrassed, as I should have caught that when writing tests, but the LDAP filter represented by `(*)` is invalid, and thus having the `toLDAPFilterString` method return such a filter when an empty predicate is passed is not desirable.

It seems that the most sensible thing to do would be to have `toLDAPFilterString` throw when such input is passed. We could provide an additional `isEmpty` method on the `Predicate` class's prototype that would return `true` if it's empty, and users could use that method to determine whether calling `toLDAPFilterString` is actually useful. This method would currently be identical to `trivial()`, but my understanding is that `trivial()` could evolve into something different in the future.

Anyway, making `toLDAPFilterString` throw on some input would be a backward incompatible change that would usually mandate a bump in the major version number. Since the current version of node-krill is in the 0.x range, and node-krill doesn't seem to have a significant numbers of dependents, I'm not sure what would be the most pragmatic solution.

What do you think about the proposal above?

**Comment by davepacheco** [comment]
I think trivial() is indeed the function you want.  We should document that trivial predicates cannot be serialized as LDAP filters, and the error message should probably indicate that.  I don't think this really requires a major version bump, but it may be time to release v1.0.0 anyway.

**Comment by misterdjules** [comment]
Fixed by a438574c2b0c9004fe98ba93449239e9776a372a.
